version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt

  test:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Run unit tests
          command: pytest tests/

  build_docker:
    docker:
      - image: circleci/python:3.8
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build Docker image
          command: docker build -t yourdockerhubusername/devsecops-app .

  push_docker:
    docker:
      - image: circleci/python:3.8
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Log in to Docker Hub
          command: echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Push Docker image
          command: docker push yourdockerhubusername/devsecops-app

workflows:
  version: 2
  devsecops_pipeline:
    jobs:
      - build
      - test
      - build_docker
      - push_docker
